server:
  port: 7010
spring:
  application:
    name: shop
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@lnb:7000/eureka/