server:
  port: 7000 #指定运行端口
spring:
  application:
    name: eureka #指定服务名称
  security:
    user:
      name: admin
      password: admin
eureka:
  instance:
    hostname: lnb #指定主机地址
  client:
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      defaultZone: http://lnb:7000/eureka/
  server:
    enable-self-preservation: true  #关闭保护模式